# -*- coding: utf-8 -*-
"""M.L.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MHOVlKMToGkdobBbrfTYN-8bIkDCYnwC
"""

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

from sklearn.model_selection import train_test_split

df=pd.read_csv("/content/uttar pradesh general elections.xlsx.csv")

df

df.info()

df.isnull().sum()

df.columns

df.isnull()

sns.heatmap(df.isnull())

df.isnull().sum()

df.info()

plt.hist(df)
plt.show()

df.Difference

df.Difference.value_counts()

df.columns

df['Difference'].value_counts()

df['Difference'].unique()

plt.figure(figsize=(4,5))
sns.countplot(x='Difference',data=df)
plt.title('Difference')
plt.show()

plt.figure(figsize=(6,6))
df['Difference > Margin'].value_counts().plot.pie(autopct='%1.1f%%', startangle=90)
plt.title('Distribution of Difference > Margin')
plt.ylabel('')
plt.show()

